Added a check to see if the player in question is an NPC.
Without this check, in an SP game with NPCs, the error below is spammed due to the frequency of OnPlayerUpdate
-----------------------------------------
function: hardytrait -- file: MoreTraits.lua line # 1705 | MOD: More Traits
function: MainPlayerUpdate -- file: MoreTraits.lua line # 4316 | MOD: More Traits

ERROR: General     , 1688855221152> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: __lt not defined for operand at KahluaUtil.fail line:82.
ERROR: General     , 1688855221152> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: __lt not defined for operand
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)